// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwr-UT7Fw99NuU3w--71sukTrEp4QrwPE',
    appId: '1:255382565242:web:5efbd96fca48a26668a6c3',
    messagingSenderId: '255382565242',
    projectId: 'tt007-projekt',
    authDomain: 'tt007-projekt.firebaseapp.com',
    storageBucket: 'tt007-projekt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUnjonilXIuU7Tnmfc-whrY8RIOc3U9Q',
    appId: '1:255382565242:android:fba679c44363d71c68a6c3',
    messagingSenderId: '255382565242',
    projectId: 'tt007-projekt',
    storageBucket: 'tt007-projekt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGlA1ySf0AZesE3ZxARoxsJ83yBPxQco',
    appId: '1:255382565242:ios:67ba72b8f556d7d868a6c3',
    messagingSenderId: '255382565242',
    projectId: 'tt007-projekt',
    storageBucket: 'tt007-projekt.appspot.com',
    iosBundleId: 'com.example.physicstool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUGlA1ySf0AZesE3ZxARoxsJ83yBPxQco',
    appId: '1:255382565242:ios:67ba72b8f556d7d868a6c3',
    messagingSenderId: '255382565242',
    projectId: 'tt007-projekt',
    storageBucket: 'tt007-projekt.appspot.com',
    iosBundleId: 'com.example.physicstool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwr-UT7Fw99NuU3w--71sukTrEp4QrwPE',
    appId: '1:255382565242:web:6f0599235ea5bbaa68a6c3',
    messagingSenderId: '255382565242',
    projectId: 'tt007-projekt',
    authDomain: 'tt007-projekt.firebaseapp.com',
    storageBucket: 'tt007-projekt.appspot.com',
  );
}
